{
 "title": "Freelancer-s2i",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GET Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_example_freelancer_rest_FreelancerResource_countFindAll_total"
    },
    {
     "expr": "application_com_example_freelancer_rest_FreelancerResource_countFindById_total"
    }
   ]
  },
  {
   "title": "HeapSize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_memory_usedHeap_bytes" },
    { "expr": "base_memory_maxHeap_bytes" }
   ]
  },
  {
   "title": "Max Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "application_com_example_freelancer_rest_FreelancerResource_timeFindAll_max_seconds"
    }
   ]
  },
  {
   "title": "Process CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent"
    }
   ]
  }
 ]
}